java_binary(
  name = 'proximitySimulationNoGUI',
  deps = [
    '//java/org/denovogroup/rangzen/simulation:simulation',
  ],
  main_class = 'org.denovogroup.rangzen.simulation.ProximitySimulation',
)
java_binary(
  name = 'proximitySimulation',
  deps = [
    '//java/org/denovogroup/rangzen/simulation:simulation',
  ],
  main_class = 'org.denovogroup.rangzen.simulation.ProximitySimulationWithGUI',
)
java_binary(
  name = 'stAndrewsSimulationNoGUI',
  deps = [
    '//java/org/denovogroup/rangzen/simulation:simulation',
  ],
  main_class = 'org.denovogroup.rangzen.simulation.StAndrewsSimulation',
)
