// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/barathraghavan/code/murmur/murmur/buck-out/gen/proto-repo/compile_protobufs__srcs/CleartextFriends.proto
package org.denovogroup.murmur.objects;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Protobuf representation of a list of friends (represented as strings) to be
 * sent in the clear over the wire to a communication partner. This is used in
 * the simplified implementation without crypto and SHOULD NOT BE USED when
 * private-set intersection is in use.
 */
public final class CleartextFriends extends Message {

  public static final List<String> DEFAULT_FRIENDS = Collections.emptyList();
    private static final String LIST_KEY = "friends";

  /**
   * A list of friends, represented as opaque String-encoded friend ids.
   */
  public final List<String> friends;

  public CleartextFriends(ArrayList<String> friends) {
    this.friends = (List<String>) friends.clone();
  }

    public JSONObject toJson(){
        JSONObject json = new JSONObject();
        try {
            json.put(LIST_KEY, new JSONArray(friends));
        } catch (JSONException e) {
            e.printStackTrace();
        }
        return json;
    }

    public static CleartextFriends fromJSON(JSONObject json){

        List<String> friends = new ArrayList<>();
        if(json.has(LIST_KEY)){
            try {
                JSONArray jsonArray = json.getJSONArray(LIST_KEY);
                for(int i=0; i<jsonArray.length(); i++){
                    friends.add((String) jsonArray.get(i));
                }
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        return new CleartextFriends((ArrayList<String>) friends);
    }
}
